version: "2"
linters:
  default: all
  disable:
    - depguard
    - wsl
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - github.com/pdarulewski/goyoon
