// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Score struct {
	Name         sql.NullString
	Score        sql.NullInt64
	PlayedRounds sql.NullInt64
}
