// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
	"database/sql"
)

const incrementScore = `-- name: IncrementScore :exec
UPDATE scores
SET
    score = score + ?,
    played_rounds = played_rounds + 1
WHERE name = ?
`

type IncrementScoreParams struct {
	Score sql.NullInt64
	Name  sql.NullString
}

func (q *Queries) IncrementScore(ctx context.Context, arg IncrementScoreParams) error {
	_, err := q.db.ExecContext(ctx, incrementScore, arg.Score, arg.Name)
	return err
}
